

                +--------------------------------------+
                | GWDG Project log file v0.8           |
                +--------------------------------------+



// ================================= Start  GW6 =========================================

// August 20th
 (0) introduce KNUs (8 of them) as cones or variable coeff (for ROI)
  {model.cl} create two types of KNU : cones and factors  
    - a KNUcone generates an affine 
    - a KNUfactor generate a number or a percentage

// August 21st 
{input.cl} create the eight KNUs

{simul.cl} create a reset() function that allows to restart the simulation using values generated by the 
  KNU (cf. the tactical vector)

// August 25th: KNUs are working well + link with CLSERVE is OK !

// August 31st : resume on CCEMv6

introduce boolean DI : true -> direct use of disolve, false -> use old solve 
I should get rid of the old solve later when disolve is OK and tested
cool : it works ! temporart TESTsolve function lauches both algo and they return the exact same price :)
=> run a few of the test case

we turn DI to true and look at performance improvement => amazing - 20x faster

// September 15th
  - added decay for economies
  - added inflation (to be able to compute gdp$ in current dollars)
  - added kpi (lambdas) for the KNUs

  Main principles for growth 
  ==========================
      - work in constant dollars (smaller growth) : 2.4% in the past, more like 1% coming
      - decay is built it (1% per year, same for all zones)
      - tuning with ROI x InvestRate.
        RoI adjusted in time (factors : taxation: weight of redistribution, R&D investment, regulation)
        OCCAM principle: do not try to model RoI based on subfactors (should be explained in the paper) unless 
        enough data is available, or unless subloops identified.

// September 21st
  - goal : 0.5% energy intensity decline (demat) + additional sumSavings
     => reduce by 1/2
  - growth -> reduce world
      - introduced decay (1%) at world level
  - OCCAM : we have removed the marginImpact and use cancelImpact instead
  - add a KNU summary and run (calibrated on 9/21 !)
  - show the GDP in current dollars (inflation) 
  
// Septembre 22nd (to be continued during trips)
   - strategy: c.satisfaction = weight of the three pains (Economy, Climate, Energy)
        -> Economy Pain = Zone economy growth * health of material economy
        game.cl : code the new compurteSatisfaction function () + 
                  new economy pain function (factors material economly growth)
                  based on the growth of (Result/c.pop * (agro + steel)/wordPop)

   - tactic : (all Percentage) taxStartn,taxFromPain, transitionStart,transitionFromPain, 
                               cancelStart,cancelFromPain, 

   gtes.cl :  new file with best response (classical local opt + randomized 2opt)
   implement best response for consumer (optimize tactics to improve strategic satisfaction)
    - code satisfaction (satScore(c))
    - code bestResponse(c) => find the best tactic for a consumer

// September 28th
   - introduce India as a separate zone  
      - zones = (US, EU, CN, India, Rest), 5 x 5 trade matrix
  - we do not replace "economy" by "model"  > current approach has its own merits 
    (everything related to econony/M4 is in the Block object)
  - retune using automation
      - script file
      - produces a log file "Result-date"
      - easy to compare with previous runs

// Tune energy production (M1)
  (a) new getOutput(Supplier) => use getMaxCapacity
  (b) getMaxCapacity => average over two years (to avoid oscillations)
  (c) getOutput does not go over Cmax, but at low price factor the reduction (dynMaxCapacity)
  (d) InfiniteSupplier is not changed yet

// October 5th, 61st birthday ! solved the issues with M1
  - fixed a bug in getMaxCapacity (addedCapacity, not addition)
  - 10 years average price
  - the formula that uses Inventory/threshold is a function (inventoryToMaxCapacity) and is now stepwise Affine
  - we reintroduced the quadratic behavior of getOutput (to reduce output for really low price)
          f1 := min(cMax, max(0.0, cProd * (1 + (pRatio - 1) * s.sensitivity) * pRatio))

// October 20th : move to BestResponse
   - manual tuning seems to work (cf tables in scenario.cl, Part 3)
   - topt(EU,i) performs a local-opt loop

// October 26th
- showSensitivity(s,y) : show the sensitivity of the output to the price
- fix the early years oscillations go(4)
- make sure that global price follows the global volume / alpha 
- see that the effect of inventory around equilibrium is not too stron

// Beatrice Birthday !!
- start a new KISS version of CCEM v6 without savings and where demat is the key belief
- remove savings (completely : KISS = demat > needs > cancel > conso > substitution)
- perform a proper calibration by zone for demat
- tune go(10) to each zone (GDP, energy) and each energy (total, price,zone)

// October 28th
 - problem: we use different formulas for the impact of trade (with or w/o protectionism) on 
    (a) needs (getNeed in game.cl)
    (b) results (gdp growth = maxOut - protectionism)
   KISS: compute a protectionism factor that does not depend on local growth 
     -> use it the same way for needs and results

  -> tune GDP (seems OK, pilot with ROI)
  -> tune energy using eTable (pilot with Demat)  
  -> tune the price of energy (pilot with sensitivity)

  New Capacity Model
    (a) capacityFactor = 110%  (model parameter)

// October 29th
  - capacity now integrates addition of the previous year (Inventory-based reduction applied)
  - fixed a bug in balanceEnergy
  - smooth inventoryToMaxCapacity (factor -> 0.1) to avoid oscillations

// October 30th 
 - reimplemented "dynamic capacity" -> in getOutput (Oil)
 - simplified Inventory management


// November 1st
- introduced a population model that does not work (too many oscillations => crazy GDP output)
- introduced the productivityFactor (still to be tested)

// November 9th
(1) - fertility is too narrow : 
     => pain to Population : réduction of birth / increase deaths (unified because indistingable ) 
     - show in M5 !  redo,picture 
      Hence : +T implies reduction of potential / plus pain / pain reduces population and efficiency (désengagement, absentéisme. strikes, wars) 

(2) reintroduced savings : voluntary efficiency gains based on investments 
    NOTE: contrary to transition which is set to 100% by default, savings are set to 0% by default  
      - model.cl: 
            c.savingRates : actual rate whose increase trigger investments,
            c.savings = list<Energy>, c.savingFactors[y] : policy (setup by redirection)
            Input (Consumer): maxSaving (for each c, max total gain until 2100), yearlySaving (max yearly increase, set to maxSavings/90) 
            Tactic : savingStart, savingFromPain
      - game.cl:
            getDematerialize(b:Block,y:Year) :  get(b.dematerialize,yearF(y)) + c.savingFactors[y - 1] 
            saves(c,s,y) : sets the new level of savingRate, bookkeeping of saved energy, computes associated investments
            redirection(s,y) : sets the saving ambution (savingFactor) according to the pain level
      - simul.cl: initialize all slots + set yearlySaving
      - display.cl: show in hist(e) and hM2

(3) changed h5+/h5- with multiply% vs improve% (cancel at start is zero)
    added an assertion in simul.cl (init(c))
    h8/h8+ : added India to the modif ! + retune cancellation

// November 10th -> run all tests 
// November 11th -> simpler distaster management for M5
   -> maxout is no longer impacted
   -> result is reduced each year by the appropriate factor

// November 16th
 - simplify the meaning of heat%(transition) = fraction (H to H), the rest produces elec (E to E or H to E)
  hence the formula in eTransferRatio is X (quantity) * (1 - r1) * (1 - heat%)
  heat% = 100 -> no impact, heat% -> 100% electrification -> gain is X * (1 - r1)

// MOVE TO ARTICLE SINCE THE COMPLETE RUNGW TEST IS OK


// January 1st, 2025 = prepare to push to GitHub
   - claire4 -m gw6 works
  - claire4 -cm gw6 works (after small cleanup of old functions)
  - work on gw1(c2j) to make sure that
       (a) code is diet
       (b) generated code is clean
       (c) generated code works


// January 2nd : reorganize so that KNU cones are part of gw6 but not sgw6 (simple version)
  - moved KNU, KNUcones and KNUfactors to gtes.cl
  - code moved from model.cl (only keep the KNU store -> will be used for GW2S) and from simul.cl
  - the instance values moved from input.cl to scenario.cl

// ==============================  March 23rd, 2025 : start CCEM v7  ==========================================================
backlog:
   (1) better damage model : better calibration (see associated CCEMv7 PPT)
   (2) adaptation
   (3) CO2 absobtion model (TCRE)
   (4) tech lifecycle downcost model (price decreases not in time but as a function of volume)
   (5) scripting
        - generates experiments = (belief => scenario)
          belief = set of hypotheses (KNU instantiation)
        - scripting = language to produce experiments (what we shall do with sliders)
   (6) Measures (copy from older GTES files)
        - be able to run multiple randomized experiments and produce stats (mean & stdev)

// March 25th 
model.cl change 
    - on new KNU to represent adaptation (as a fraction (invest costs / yearly max savings)
    - Consumer: adapt slot => Adaptation object (adaptSpend, adaptSum, adaptEffiency) + 
      tactic (adaptStart, adaptFromPain)
    - Damages & TCRE :  Gaia has TCRE (Affine) and co2Cumuls 
    - simplifier la satisfaction 3P (People, Profit, Planet) 

Scenario.cl : new KNUs
    - rename old KNUs
    - add Kadapt and Khuman
    - each KNU has onto:Set and modify:property that tells how to apply the "cursor" (G2WS)
    - World has a global protectionism factor that moves both in and out ratios

// April 12th (until 15th)
// extended week-end goal : write code (coarse) + move to PC (start tuning in US)

Create (model.cl)
      - Tmeasure :: list<measure>
      - Charts :: sets of Tmeasures for Earth, Consumer, Supplier
      
Produce (simul.cl)
      - updateCharts()
      - makeCharts()  : creates the empty chars (list of measures)

gtes.cl   
    -  Belief : list of KNU(name), value
    - runBelief(l) : apply the float values to each KNU of the belief
    - script(c, strategy, ...) : creates a belief
    - randomize(c, strategy, ...) : runs a complete simulation loop 
         (a) MonteCarlo instantiation
         (b) run the simulation
         (c) records the results into the charts
         (d) produces a report

game.cl : introduce CCEM v7 changes
    - damages are mitigated by adaptation levels
    - adaptation levels are modified through the tactics


input.cl : introduce adaptation + TCRE


// April 16th : USA vacation starts :)  
// May 1st: move back to Mac

(a) big decision : v7 energy is based on https://ourworldindata.org/energy-mix
    however:  Electricity is picked on https://ourworldindata.org/electricity-mix
    -> change input.cl (2010)
(b) tune energy  -> add transfers to match 2019  -> done on 2nd of May at 9:30
      - coal to clean in CN 
      - oil to clean in EU 
(c) check 2024 - 2050 - 2100 hypothesis for transfers
      -> hypothesis for energy shares in 2100  
(d) check electricity rates in 2010, 2020, 2040 with eTable  -> add tr.efficiency% as a factor for eRatio (c.ePWHs)

// May 9th
- TRCE immplemented (TCRE slot + CO2cumuls) -> no worsening impact
- re-run damages/adaptation hypothesis
      -> added w.adaptGrowthLoss (May 10th)   -> removed on June 14th
      -> recompute spend with c.tactics.adaptMax at 20%

// May 10th : recalibrate the warming model according to last IPCC model
- RPCC 4.5  -> 2.7
- RPCC 6.0  -> 3.2
h11(5% or 10%) give a good Nordhaus simulation at +3C

// May 17th : play with auto-tune for adaptation

// May 31st : start the "June CCEM" experiments (as show in the slide of CCEMv7)
// June 1st:
      - whatif to see what happens with a small change, then makeTable, then topt(c,p).
      - played with Carbon tax : best strategy is 0 (slows economy and does not reduce CO2 because of other players)
      - played with energy transition: best strategy is 100% (accelerate) because CCEMv7 does not capture well
        the cost of transition 

// Bonnieux week-end (June 7th)
- trace transfert for Europe and associated costs : 2PWh to Clean shoulf cost 2T$ (1T$ per PWh)
  compare h0 with h00 (EU.tactic.transitionStart := 0%)
- may add a transition cost factor (transitionCostFactor) (1$ in transition for 1$ in energy supply)

// RESULTS (June 7th)
- there was a bug with the transition cost factor (should us tr.to.investPrice)
- we have created two temporary slots investCapacity and investTransition to decompose investEnergy

// June 8th & 9th : implement better BR (Best Response)
// interesting : find the best tactic for Europe and China (transitionStart, transitionFromPain
gtes.cl
   -  created topt (test dichotomic opt / fixed !) and topts (with sampling: more robust)
   -  created toptp (test a pair of bound properties) : nested sampling
   - interesting results for Europe and China => best tactic is different for h0 and h00
    if no one transitions, then the best tactic is transition more ...

// June 14th & 15th : adaptation tuning
   - input.cl adaptation affine curve is simpler
      before: expressing total adaptation spend as a fraction of total property costs 
         (10-15% for real estate, 10% for Michelin, 50T$ for 500T$ with revised GPT estimates)
  - game.cl : 
      - simpler attenuation
      - make sure that we record total spend and total avoided damages  -> c.adapt.gains
  - display.cl :  hM6(c) shows the adaptation spend and gains
  - gtes.cl        topt(c) -> complete optim and show(c.tactic)

// June 20th : changed completion to Claude
Open the command palette by pressingCommand+Shift+P (Mac). 
Type change completions model and select the "GitHub Copilot: Change Completions Model" command.
In the dropdown menu, select the model you want to use.

// extends CCEMV7 for CBAM simulation
   - (1) add "ajust for trade" consumer emissions (add imports at the export level of CO2/$ and remove exports at the local leve)
         AjustForTrade(c:Consumer,y:Year) : float
   - (2) compute 2010 values and compare with our sources: OCDE and ourworldindata -> seems OK!
          EU: 3.59 to 4.185 = growth 16.5%
          
   - (3) change 3P satisfaction: planet is based on CO2 emissions "adjusted for trade" reductions until 2050
       display.cl  trade(c:Consumer,y:Year) : void show the trade flows
           new GDP x TradeMatrix x importReduction  


// August 2025
      - improved the web.cl file to work with clserve.go
      - model.cl : added scalarProduct and boundedProduct
      - game.cl: averagePain (3 years) for productivityFactor (avoid oscillations)


// =========================== Oct 5th, 2025 (62th birdthday) : start v8 ========================


Oct 5th: démarre le fichier input80.cl 
Oct 12th: update Google doc with 1980 data & energy sector data (EIA & GPT5)
Oct 19th: write excel support files "EnergySensity","EnergyMatrix.xlsx"
Oct 24th: write GDP Data Mining excel file
Oct 26th: start coding : SETM, ETM, densityCurve, elasticityCurve
Oct 27th: New RoI formulation
  RoI = world.RoI(24%) * zone.techFactor(KNU) * (1 - zone.socialExpenseRatio)^2 - decay(GDP/h)
  decay = 0% until 2000 (1980 $), 2% until 5000, 5% after

Oct 29th  go(10): raw debug
          found a bug in the Excel "GDP Data mining" -> new techFactor and decay
          go(30): tune to get 2010 value
          check : energy prices are OK in 1990 (no increases)

MEGA-DECISION1: we do not use populationGrowth any more as a factor
    (a) M1 : for energy needs
    (b) M4 : for Maxout (GDP growth)
    hence popEnergy is gone :)

Oct 30th : tune energy consumption up to 2020 (go(30)) to ensure that transfers do occur
           using eTable()

MEGA-DECISION2: we compute inverstGrowth irrespectively of energy (how we calibrate the model)
    note: we could return later to impacting InverstG from investE  
    we also decide to make c.decayTable a time-affine for each zone.

    the following matrix should be in CCEMV8 PPT
+-----------------------------------------------------------------------------------------------------+
| TUNING PROTOCOL (we need this to be simple)                                                         |
+-----------------------------------------------------------------------------------------------------+
|    (1) GDP tuning thanks to RoI, techFactor, decay  (source GDPDataMining.xls)                      |
|        mesure results and maxout (see the effect of energy shortage & damages)                      |
|        first tune US based on world.RoI, then others on tech factor                                 |
|    (2) Energy consumption by zone thanks to demat curves ()                                         |
|        first tune total by zone through demat, without transfer (use notransfer() in input)         |
|    (3) Energy price tuning thanks to sensitivity curves and growth capacity                         |
|        this is required to ensure that cancellation is minimal before fine tuning - including (2)   |
|        it also requires that transition is active  (stop using notransfer())                                                 |
|    (4) Energy by source tuning thanks to ETM (subMatrix)  (source EnergyMatrix.xlsx vs eTable)      |
|        note that fine tuning cannot be done before (3)                                              |
|    (5) check electricity consumption through elTable                                                |
|        play with heat% in transition, then adjust the speed of transitions to balance elec%(zone)   |                                              |
|    (6) move to longer time horizon to tune cancellation effects                                     |
|        it can also be tested while lowering inventories - check that price increase make sense      |
|        check cancel curve consistency (from 0 to 99% at PMAX)                                       |
|    (7) iterative process since there are dependencies:  (1) to (4)                                  |
|    (8) check steel and wheat production (adjust density & crop yield)                               |
+-----------------------------------------------------------------------------------------------------+


October 31st: revise energy supply (M1)
---------------------------------------
   MEGA-DECISION 3: create expectedPrice (based on production price, without shortage or surplus)
     - the price is hard to model : it is a KNU (look at "Price" in "EnergyDensity")
       goes up for oil (1990-2020) because of shale oil, down for all others
    - one unique supplier profile (equation [1] and [2])
    - model.cl is simplified ()

    debug:  (remove transfers first)
      - check that capacity follows demand

November 1st: follow tuning PROTOCOL
------------------------------------
    (0) validate the inflation vector => https://www.minneapolisfed.org/about-us/monetary-policy/inflation-calculator
    (1) GDP tuning: (a) total : 26.9 (b) US:6.7, EU:4.84 CN:4,79 In:0.85 RoW:9.82
        note: fix dematerialization first (not enough coal)
    (2) Energy consumption   total 2020: 147  US:24.19, EU:14.8 CN:36.6 IN: 9.09 RW:64.4
   
November 8th : 
    - total energy consumption is OK
    (3) We want the source profile (2020)   Oil: 53.6, Coal: 46.6, Gas: 39.06, Clean: 9.72
        - first we need to fix the inventories (use GPT)
    (4) we need to reproduce the transfers 80 to 2020
        - same oil,  less coal, more gas, more green 
    DONE at 17:45 = we have a good energy vector by zone and by source for 2020
    (5) check electricity consumption (eTable) => we want 26.5 PWh in 2020 -> DONE
    NOTE: in CCEM v9 we need to improve the model of electricity production (too much complexity because of not enough data)
          simple idea is to separate heat/elec for each fossil fuel (we have the data when we start)

November 9th : go(120) ! got decent results at 16:00
     go(70) : look at what happens to gas price !
     the first step is to model the rarefaction of a fossil fuel
     There was 4 bugs:
        - the formula for maxCapacity, when threshold kicks in, must be continuous
        - cancelCurve must be consistent with start price (constant ORIGIN dollars) and PMAX
        - inventory as f(Price) should be discussed with experts (cf. O. Vidal)
        - threshold ratio (when we start to reduce capacity) should be 70% of starting  value
     WE need to restart ! fix go(40) before looking at go(70)
        - price of electricity is too high => do not confuse capacityOrigin and capacityMax :)
     COOL: we get proper histograms for Gas and Oil - shapes depend on beliefs about reserves

     go(120): we need to fix the growth of China by making social expenses an affine
     KEY IDEA: this is a KNU in CCEM v8, but will depend on aging and redistribution in CCEM v9
     (a) we call roiEfficiency the tuning factor that is 100% for US and factors tech and innovation
     (b) we tune China for 2010 and 2020

     - made inflation a StepFunction (to be more precise)
     - tuning of impactFactor (impact of cancel losses to investment growth)
    
  
November 10th: tune 2010 model using input2010.cl
--------------------------------------------------
     (1) expected GDP: 73.8 total, US 17.7  EU 13.7 CN 12.6  IN 2.24  RW 27.15
     (2) Energy consumption   total 2020: 147  US:24.19, EU:14.8 CN:36.6 IN: 9.09 RW:64.4
     (3) energy prices are OK
     (4) We want the source profile (2020) total 149TWh  Oil: 53.6, Coal: 46.6, Gas: 39.06, Clean: 9.72
     (5) go (90)

     good news: done !
     bad news:
        (a) growth is too high and especially China (looks like 1980 version)
        (b) need to see how much energy is here
            - proper calibration of fossil reserves
            - proper calibration of renewable growth (look at 2024)


November 11th: produce 2200 trajectories (and see if collapse will, or could, occur)
    - it works beautifully from 1980 !
    - we now need to
        (a) calibrate gw8 vs gw7, for 2010, 2050, 2100
        (b) calibrate precisely the energy input hypothesis and make them similar
             - fossil inventory 
             - capacity growth for renewables


November 16th: prepare energy data for CCEM dinner => new calibration
    - oil, gas, coal 
    - max Growth for renewable 0.3-0.5 en 2010-20 et 07-1.0 en 20-30
      need to calibrate the transition (electrification that seems to be the bottleneck)


December 1st: resume
   - electricity calibration unti 2030 : 36 000 TWh
   - need expected Oil 52 PWh, Gas: 45 PWh, Coal: 55PWh in 2030
   - recalibrate transition
       2020: looks OK (elec at  26, Oil/Gas too high/low vs EnergyMatrix.xls, same for Coal, OK for clean)
           => Oil to Gas (both Indus & Res)
           => Coal to Gas (Res)
       NOTE: when we recalibrate transition(2020) we need to recalibrate dematerialisation to get EnergyMatrix
       2030: too much coal, not enough Clean (move 4PWh)

December 6th: finish 1980 callibration
  - steel (Iron in EnergyMatrix) : zone.ironDriver (affine) in 1980 dollars, steelPrice (1980), energy4steel
  - wheat: wheatProduction, agroLand, cropYield and landImpact
  - CO2 data in 1980: ppm, emissions, cummulative emissions, world average temperature
  => enter data in input1980.cl
  - run go(40): 2020 and go(120): 2010
  - check electricity product eTable()  => works beautifully with the addition of CARNOT factor to estimate 
    s.heat% (the part that is not electricity) in simul.cl

December 7th: do 2010 calibration (input2010.cl)
    - implement painDelay (a meta parameter for World) that is used in game.cl
      this will be used to measure the value of anticipation (*FromStart vs *FromPain)
    - enter data in 2010$ : GDP,
    - run go(10)  / follow complete calibration protocol 
       => GDP tuning: (a) total 2020 : 73.8 (b) US:17.6, EU:13.7 CN:12.6 In:2.24 RoW:27.15
    - go(90)

December 14th : adress CCEM 3 shortcoming = transition control, v7 vs v8 consistent energy hypothesis, China GDP Growth
   - note: the  completed Balance of Trade matrix (2010 and 2020) show stability
   - decision : the default run (go(x)) will be done with transition at 50%.
     getTransferRate() is changed to apply transitionFactor to years post 2020 (pivot) => tuning will work
   - tune demat:  (B) Energy consumption   total 2020: 147  US:24.19, EU:14.8 CN:36.6 IN: 9.09 RW:64.4
    
Extended week-end : tune CHINA GDP 2020,2030 and 2050 using GPT5 for consensus
   - add a laborCompetitiveness factor to RoI that is an affine function to the relative (GDP/h)
   - model.cl  create the affine associated to pb.world
   - game.cl : add getCompetitiveness & laborFactor
   - input2010.cl  : first simple tuning to get 2020, 2030 and 2050 coherent (+40% peak)
  
   - input1980.cl : obtain the 2020 vector, to tune the bonus of lower labor cost
         GDP2020:  27.9 with US:6.7, EU:4.84 CN:4,79 In:0.85 RoW:10.43  [1980 US dollars]
         GDP2010:  24.94 with US:5.8, EU:5.48 CN:2.34 In:0.67 RoW:10.7

December 20th: finalize 1980 calibration
  - GDP done (2020, consistent with 2010) -> use 28% a default growth (align with input2010.cl)
       2030 / 2050 for US/China = 31/25  and 55/45 in current GDP
       we get in 2050:current GDP = 221.32T$, US: 60.32T$, EU: 26.55T$, CN: 56.09T$, IN: 13.59T$, Rest: 64.76T$,
  - energy tuning 
      (a) energy total 2020: 149TWh  US:24.19, EU:14.8 CN:36.6 IN: 9.09 RW:64.4
      (b) energy by source: total 149TWh  Oil: 53.6, Coal: 46.6, Gas: 39.06, Clean: 9.72

December 21st: 2010 calibration following the complete protocol 
   (1) GDP 2020: 73.8 total, US 17.7  EU 13.7 CN 12.6  IN 2.24  RW 27.6
       GDP 2030/2050:    US: 31 / 55    EU: 22 / 32   CN: 25 / 45  [US current $]
  (2) + (4) Energy 2020: 149 total, US 24.19  EU 14.8 CN 36.6 IN 9.09 RW 64.4
      Energy by source 2020: Oil: 53.6, Coal: 46.6, Gas: 39.06, Clean: 9.72
   (3) prices follow the KNU :)
   (5) electricity at 27 800 TWh in 2020 is good (cf Google notes)
   (6) & (7) : will do through sensitivity analysis
   (8) wheat production => 2010: 640Mt  2020:767Mt   2030: 840Mt (GPT 5.2)
       steel production => 2010:1.4Gt   2020:1.9Gt (small COVID hit)   2030:2.1Gt (GPT 5.2)
       wheat is wrong in 2011 !  => fix from input.cl :)

December 22/23 => sensitivity analysis
    - carbonTax is added to investments, pending CCEM v9 redistribution model
    - redo optimization of tactics with topt(EU) and topt(US)
        play with delays to reactions (Gaia.painDelay)
        - réaction de redirection (pain)  => allows to balance the "*start" vs "*fromPain" in the tactic
        - play with it in an optimization loop (example : adaptation)

December 24th : simulations until 2200 (go(190))  
     (1) it works !
     (2) added fullTransfers to see what if we transfer ->  slow degrowth during 22nd century (back to 95T$)
     (3) it needs to be tuned in CCEMv9 when we add pain -> redirection 
     (4) the effect: no fossil -> economy contraction -> reduction of Clean is surprising but logical (interdependecy)
     (5) the formalas for growth are brutal : RoI x Invest is less than decay for EU and RoW  

// January 4th to 11th : audit  by GPT5 based on "CCEM2025v8.ppt"
- M1 :  fixed the expected growth formula (linear regression had a bug)
- M2 : SavingRates vs SavingFactors (thanks GPT5 !), demand algebra (1-x)(1-y) vs (1- x + y), population is not a linear factor for needs
- M3:  only change equations, code is better :)
- M4: populationGrowth transformed into productionDecline, Added adaptation invest into equations
- M5: added adaptation to equations, clarified pain

// WE CLOSE AND MOVE TO G2WS ===========================================================================

change web.cl to adapt tp CCEM v8
  - 9 KNUs and 6 tactical -> 15 sliders
  - updated the Explanations
      -  fossilToCleanMax(c) : max share (from substitution matrix) of fossil that can be transitioned to clean
  - updated slider store

updated clserve.go
  - added setup option to display additional sliders : Density, RoI, populationImpact

// Bugs for Vermont
  - explanation list should be given the first time the UX is called : we need a new method in clserve (setExplanations)
    currently, it is only updated by callback

updated g2ws.go (which has the same structure)


// ideas for CCEM v9
  (a) 3 more KNUs : AI to Inequality, Inequality to Economic output, ???
  (b) Setup => separate world KNus to Zone Knus (Roi and Population Impact
  (c) some factors should change in a time-sensitive manner (nothing in 2020 up to x in 2100))















